region = "us-east-1"
aws_ecr_repository_name = "faturamento-dev"
environment_name = "dev"
aws_ecs_cluster_name = "faturamento-cluster-dev"
aws_iam_role_name = "faturamento-task-execution-role-dev"
aws_ecs_task_definition_family = "faturamento-task-dev"
aws_ecs_task_definition_name = "faturamento-task-dev"
aws_alb_name = "faturamento-lb-dev"
aws_lb_target_group_name = "faturamento-target-group-dev"
aws_ecs_service_name = "faturamento-service-dev"
backend "s3" {
    bucket = "terraform-tfstate-00000001"
    key    = "dev/terraform.tfstate"
    region = "us-east-1"
}